package:
  name: pydoe
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
   path: ../


build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

    
requirements:
  build:
    - python
    - setuptools
    - scipy

  run:
    - python
    - scipy >=0.13
    - numpy >=1.8

test:
  imports:
    - pyDOE



about:
  home: https://github.com/tisimst/pyDOE
  license: BSD License
